#Production
services:
  backend:
    build: ./backend
    container_name: bookworm-backend
    restart: always
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    container_name: bookworm-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

volumes:
  certbot-etc:
  certbot-www:









# #uncomment below for development
# services:
#   backend:
#     build: ./backend
#     container_name: bookworm-backend
#     restart: always
#     env_file:
#       - ./backend/.env

#   nginx:
#     image: nginx:latest
#     container_name: bookworm-nginx
#     restart: always
#     ports:
#       - "80:80"
#       # - "443:443"
#     depends_on:
#       - backend
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     #   - certbot-etc:/etc/letsencrypt
#     #   - certbot-www:/var/www/certbot

# #   certbot:
# #     image: certbot/certbot
# #     container_name: certbot
# #     volumes:
# #       - certbot-etc:/etc/letsencrypt
# #       - certbot-www:/var/www/certbot

# # volumes:
# #   certbot-etc:
# #   certbot-www:
